version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: bgf-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-bgf_aid_system}
      POSTGRES_USER: ${DB_USER:-bgf_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bgf_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - bgf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-bgf_user} -d ${DB_NAME:-bgf_aid_system}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: bgf-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - bgf-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bgf-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      
      # Database
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-bgf_aid_system}
      DB_USER: ${DB_USER:-bgf_user}
      DB_PASSWORD: ${DB_PASSWORD:-bgf_password}
      DATABASE_URL: postgresql://${DB_USER:-bgf_user}:${DB_PASSWORD:-bgf_password}@database:5432/${DB_NAME:-bgf_aid_system}
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      
      # CORS
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS:-true}
      
      # SendGrid Email
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      FROM_EMAIL: ${FROM_EMAIL:-noreply@bridginggapfoundation.org}
      FROM_NAME: ${FROM_NAME:-BGF Aid System}
      
      # Twilio SMS
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      
      # Optional Telegram
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      
      # Security
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      
      # Organization
      ORG_NAME: ${ORG_NAME:-Bridging Gap Foundation}
      ORG_ABBREVIATION: ${ORG_ABBREVIATION:-BGF}
      ORG_EMAIL: ${ORG_EMAIL:-info@bridginggapfoundation.org}
      ORG_PHONE: ${ORG_PHONE:-+263123456789}
      
      # URLs
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:3001}
      
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - bgf-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api/v1}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-BGF Aid System}
        NEXT_PUBLIC_ORG_NAME: ${NEXT_PUBLIC_ORG_NAME:-Bridging Gap Foundation}
    container_name: bgf-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api/v1}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-BGF Aid System}
      NEXT_PUBLIC_ORG_NAME: ${NEXT_PUBLIC_ORG_NAME:-Bridging Gap Foundation}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - bgf-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: bgf-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - bgf-network
    depends_on:
      - frontend
      - backend
    profiles:
      - production

  # Backup Service
  backup:
    image: postgres:15-alpine
    container_name: bgf-backup
    restart: "no"
    environment:
      PGPASSWORD: ${DB_PASSWORD:-bgf_password}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    networks:
      - bgf-network
    depends_on:
      - database
    profiles:
      - backup
    command: /backup.sh

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  bgf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
